"""Scheduling a design-review Calendar event with a Meet link.

One endpoint: insert on the ``primary`` calendar with
``conferenceDataVersion=1``, which is what allows the ``createRequest`` that
makes Google mint a Meet link server-side. The event is titled after the
board and the description carries the review's blockers -- the event exists
*because* the review found blockers, so they are the agenda.

Nothing here decides whether to schedule; that judgment (blockers or not)
belongs to the caller in ``__main__``, and it says out loud either way.
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass

from .auth import RERUN_HINT, AuthError
from .transport import GoogleError, HttpRequest, Transport, ensure_google_url

__all__ = ["EVENTS_URL", "ScheduledEvent", "schedule_review"]

EVENTS_URL = (
    "https://www.googleapis.com/calendar/v3/calendars/primary/events"
    "?conferenceDataVersion=1"
)

#: Reviews default to tomorrow, same time, for half an hour: soon enough to
#: matter, far enough that attendees can actually come.
DEFAULT_LEAD_S = 24 * 3600
DEFAULT_DURATION_S = 30 * 60


@dataclass(frozen=True)
class ScheduledEvent:
    html_link: str
    meet_uri: str


def _rfc3339(epoch: float) -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(epoch))


def schedule_review(
    token: str,
    *,
    board_name: str,
    blocker_titles: list[str],
    attendees: list[str],
    transport: Transport,
    now: float | None = None,
    request_id: str | None = None,
) -> ScheduledEvent:
    """Create the review event; returns its link and the Meet URI."""
    start = (time.time() if now is None else now) + DEFAULT_LEAD_S
    agenda = "\n".join(f"- {title}" for title in blocker_titles)
    body = {
        "summary": f"Design review: {board_name}",
        "description": (
            "The silkscreen adversarial review found blocking findings on "
            f"{board_name}:\n{agenda}\n\nGenerated by python -m googleapps."
        ),
        "start": {"dateTime": _rfc3339(start), "timeZone": "UTC"},
        "end": {"dateTime": _rfc3339(start + DEFAULT_DURATION_S), "timeZone": "UTC"},
        "attendees": [{"email": address} for address in attendees],
        "conferenceData": {
            "createRequest": {
                # Idempotency handle: retrying with the same id cannot mint
                # a second conference.
                "requestId": request_id or uuid.uuid4().hex,
                "conferenceSolutionKey": {"type": "hangoutsMeet"},
            }
        },
    }
    response = transport(
        HttpRequest(
            "POST",
            ensure_google_url(EVENTS_URL),
            {
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json; charset=utf-8",
            },
            json.dumps(body).encode("utf-8"),
        )
    )
    if response.status == 401:
        raise AuthError(f"Calendar rejected the access token; {RERUN_HINT}")
    payload = response.json()
    if response.status >= 300:
        detail = str((payload.get("error") or {}).get("message") or "insert failed")
        raise GoogleError(f"http_{response.status}", detail)

    meet = ""
    for entry in (payload.get("conferenceData") or {}).get("entryPoints") or []:
        if entry.get("entryPointType") == "video":
            meet = str(entry.get("uri") or "")
            break
    meet = meet or str(payload.get("hangoutLink") or "")
    return ScheduledEvent(
        html_link=str(payload.get("htmlLink", "")), meet_uri=meet
    )
