import type { Metadata } from "next";
import { Geist, Geist_Mono, Libertinus_Serif, Fugaz_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const libertinusSerif = Libertinus_Serif({
  variable: "--font-libertinus-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const fugazOne = Fugaz_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-fugaz-one",
});

export const metadata: Metadata = {
  title: "Silkscreen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${libertinusSerif.variable} ${fugazOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
